### ISSUE TITLE
Problem with new Django release

### ISSUE THREAD

**Issue by Mogost** [arteria/django-hijack-admin#16]
Could not find a version that matches Django<1.12,==2.0,>=1.2,>=1.3,>=1.4,>=1.5,>=1.8

**Comment by walterrenner** [comment]
What Django version is installed?

django-hijack and django-hijack-admin have no official support for Django 2.0 yet.

**Comment by Mogost** [comment]
Yes. Django 2.0. Will be supported or only LTS versions are supported?

**Comment by walterrenner** [comment]
Absolutely not. We are aiming to support Django 2.0 ASAP. See https://github.com/arteria/django-hijack/issues/149

**Comment by Mogost** [comment]
Thank you!
