### ISSUE TITLE
Warning always appears when using custom user model

### ISSUE THREAD

**Issue by frewsxcv** [arteria/django-hijack-admin#2]
https://github.com/arteria/django-hijack-admin/blob/e0773ff37777badfd35cf2d6ce09dfd5e46e536d/hijack_admin/checks.py#L23-L34

This warning seems to unconditionally appear when using a custom user model, even if one has the `HijackUserAdminMixin` mixed into their custom `UserAdmin`.

```
WARNINGS:
user.User: (hijack_admin.W001) django-hijack-admin does not work out the box with a custom user model.
	HINT: Please mix HijackUserAdminMixin into your custom UserAdmin.
```

**Comment by utapyngo** [comment]
Will you please release this fix?

**Comment by walterrenner** [comment]
@utapyngo this Issue is still open. If you take a look at #3 you can see the tests have failed and the coverage decreases.

We'll release a new version as soon as this Issue can be closed.

**Comment by frewsxcv** [comment]
I can look into writing a test for that PR later today.

**Comment by frewsxcv** [comment]
Added a working test. Coverage no longer decreases. 🎊
