### ISSUE TITLE
[bug] Duplicates hijacked session after click on the same user

### ISSUE THREAD

**Issue by koddr** [arteria/django-hijack-admin#20]
Hello!

I found interesting bug. If I click hijack button in Django admin panel (for example, `user@example.com`) and return back and click the same button — hijacked session for this user was duplicates! 

And I need to click `Release user@exmaple.com` twice (or more, equal to click `hijack user@example.com` in admin panel).

Would be great to fix this bug 👍 
My idea is simply hide `hijack user` button in admin panel, if this user is already hijacked. And, maybe, place small badge like `Already hijacked` for more understanding.

Thanks, btw, awesome library!

**Comment by walterrenner** [comment]
Hi @koddr. Thanks for pointing this out.

Can you provide a test case where this behaviour can be reproduced, so we easily can work on a fix.

**Comment by koddr** [comment]
@walterrenner it's simple to reproduce:

- First: click `Log in as ...`:

<img width="1095" alt="screen shot 2018-02-16 at 11 26 41" src="https://user-images.githubusercontent.com/11155743/36299092-8158ab08-130c-11e8-8f13-9a53c60d2ece.png">

- Second: (after redirect) go to that admin page and click to `Log in as ...` again (on same user).
- Finally: go to page, were hijack panel is showing and click `Release ...`. 
- After redirect, go to that page — nothing to happen, user is still hijacked!
- If you click `Release ...` again — user is un-hijacked (because we click `Log in as ...` twice).

Would be nice to hide `Log in as ...` button in admin page, if user is already hijacked.

**Comment by philippeowagner** [comment]
This works as designed and is not a bug. Technically it's not a duplicate, it's another hijacked user in the history. Hijack stacks all logins, see here: 

https://github.com/arteria/django-hijack/blob/master/hijack/helpers.py#L122-L123

 
Your back button works because the hijacked user has the access rights to the admin as well.
