### ISSUE TITLE
Could this depend on django-hijack>=2.1.2?

### ISSUE THREAD

**Issue by Flimm** [arteria/django-hijack-admin#8]
Currently, in `setup.py`, one of the requirements is `django-hijack==2.1.2`. However, the latest version of [`django-hijack`](https://pypi.python.org/pypi/django-hijack) is 2.1.3.

Could the `install_requires` of `setup.py` be more accepting of newer versions of `django-hijack`?

Some people pin specific versions in `requirements.txt`, and put the allowed version ranges in `install_requires`, but that's up to you.

**Comment by Flimm** [comment]
I now see that both this package and `django-hijack-admin` are made by the same author and seem to go together. In that case, I guess the dependency should just be bumped.

**Comment by jvamvas** [comment]
@Flimm Thank you for reporting this issue :)  From the next release on, we will specify the requirement in a `>=`-like manner.
